export const actionTypes = {
  
  GET_PROPERTIES_LOADING: "GET_PROPERTIES_LOADING",
  GET_PROPERTIES_SUCCESS: "GET_PROPERTIES_SUCCESS",
  GET_PROPERTIES_FAIL: "GET_PROPERTIES_FAIL",

  CREATE_PROPERTIES_LOADING: "CREATE_PROPERTIES_LOADING",
  CREATE_PROPERTIES_SUCCESS: "CREATE_PROPERTIES_SUCCESS",
  CREATE_PROPERTIES_FAIL: "CREATE_PROPERTIES_FAIL",

  UPDATE_PROPERTIES_LOADING: "UPDATE_PROPERTIES_LOADING",
  UPDATE_PROPERTIES_SUCCESS: "UPDATE_PROPERTIES_SUCCESS",
  UPDATE_PROPERTIES_FAIL: "UPDATE_PROPERTIES_FAIL",

  DELETE_PROPERTIES_LOADING: "DELETE_PROPERTIES_LOADING",
  DELETE_PROPERTIES_SUCCESS: "DELETE_PROPERTIES_SUCCESS",
  DELETE_PROPERTIES_FAIL: "DELETE_PROPERTIES_FAIL",
};
