export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";

export const GET_SOCCER_BOOKINGS = "GET_SOCCER_BOOKINGS";
export const CREATED_BOOKING = "CREATED_BOOKING";
export const CREATE_BOOKING_FAIL = "CREATE_BOOKING_FAIL";
export const CREATE_BOOKING_LOADING = "CREATE_BOOKING_LOADING";
export const TOOGLE = "TOOGLE";
export const TOOGLE_CANCEL = "TOOGLE_CANCEL";
export const GET_BOOKING_DETAILS = "GET_BOOKING_DETAILS";
export const UPDATE_BOOKING_LOADING = "UPDATE_BOOKING_LOADING";
export const BOOKING_UPDATED = "BOOKING_UPDATED";
export const GET_CLIENTS = "GET_CLIENTS";
export const CANCEL_BOOKING_LOADING = "CANCEL_BOOKING_LOADING";
export const CANCELLED = "CANCELLED";
export const GET_STATS = "GET_STATS";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CLEAR_MESSAGES_SUCCESS = "CLEAR_MESSAGES_SUCCESS";

// export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
